import argparse
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATA_ROOT = REPO_ROOT / "datasets" / "vintext_recognition"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "weights" / "vietocr_vintext"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Fine-tune VietOCR on prepared VinText recognition crops."
    )
    parser.add_argument(
        "--data-root",
        type=Path,
        default=DEFAULT_DATA_ROOT,
        help="Recognition dataset root generated by prepare_vintext_vietocr.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Output directory for VietOCR config, logs, checkpoints, and export weights.",
    )
    parser.add_argument(
        "--config-name",
        default="vgg_transformer",
        help="VietOCR base config name. Common values: vgg_transformer, vgg_seq2seq.",
    )
    parser.add_argument(
        "--device",
        default="cuda:0",
        help="Training device, e.g. cuda:0 or cpu.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=16,
        help="Training batch size.",
    )
    parser.add_argument(
        "--iters",
        type=int,
        default=20000,
        help="Number of VietOCR training iterations.",
    )
    parser.add_argument(
        "--num-workers",
        type=int,
        default=2,
        help="Dataloader workers.",
    )
    parser.add_argument(
        "--valid-every",
        type=int,
        default=1000,
        help="Validation interval in iterations.",
    )
    parser.add_argument(
        "--print-every",
        type=int,
        default=100,
        help="Logging interval in iterations.",
    )
    parser.add_argument(
        "--max-lr",
        type=float,
        default=0.0003,
        help="Maximum learning rate.",
    )
    parser.add_argument(
        "--write-config-only",
        action="store_true",
        help="Only write config.yml and do not start training.",
    )
    parser.add_argument(
        "--no-pretrained",
        action="store_true",
        help="Do not load VietOCR pretrained weights before fine-tuning.",
    )
    return parser.parse_args()


def require_training_files(data_root: Path):
    required = [
        data_root / "labels" / "train.txt",
        data_root / "labels" / "val.txt",
    ]
    missing = [path for path in required if not path.exists()]
    if missing:
        missing_list = "\n".join(f"  - {path}" for path in missing)
        raise FileNotFoundError(
            "Missing VietOCR dataset label files:\n"
            f"{missing_list}\n"
            "Run tools/prepare_vintext_vietocr.py first."
        )


def build_config(args):
    try:
        from vietocr.tool.config import Cfg
    except ImportError as exc:
        raise ImportError(
            "The vietocr package is required for this script.\n"
            "Install with: pip install vietocr"
        ) from exc

    config = Cfg.load_config_from_name(args.config_name)
    data_root = args.data_root.resolve()
    output_dir = args.output_dir.resolve()
    checkpoint_dir = output_dir / "checkpoints"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    config["device"] = args.device
    config["dataset"]["name"] = "vintext"
    config["dataset"]["data_root"] = str(data_root)
    config["dataset"]["train_annotation"] = "labels/train.txt"
    config["dataset"]["valid_annotation"] = "labels/val.txt"
    config["dataloader"]["num_workers"] = args.num_workers
    config["trainer"]["batch_size"] = args.batch_size
    config["trainer"]["iters"] = args.iters
    config["trainer"]["valid_every"] = args.valid_every
    config["trainer"]["print_every"] = args.print_every
    config["trainer"]["checkpoint"] = str(checkpoint_dir / "transformerocr_checkpoint.pth")
    config["trainer"]["export"] = str(output_dir / "transformerocr.pth")
    config["trainer"]["log"] = str(output_dir / "train.log")
    config["optimizer"]["max_lr"] = args.max_lr
    config["predictor"]["beamsearch"] = False
    config["quiet"] = False
    return config


def write_config(config, output_dir: Path):
    try:
        import yaml
    except ImportError as exc:
        raise ImportError(
            "PyYAML is required to write VietOCR config.yml.\n"
            "Install with: pip install pyyaml"
        ) from exc

    output_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / "config.yml"
    with config_path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(to_plain_data(config), handle, allow_unicode=True, sort_keys=False)
    return config_path


def to_plain_data(value):
    if isinstance(value, dict):
        return {key: to_plain_data(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [to_plain_data(item) for item in value]
    return value


def train(config, pretrained: bool):
    try:
        from vietocr.model.trainer import Trainer
    except ImportError as exc:
        raise ImportError(
            "The vietocr package is required for training.\n"
            "Install with: pip install vietocr"
        ) from exc

    trainer = Trainer(config, pretrained=pretrained)
    trainer.train()


def main():
    args = parse_args()
    data_root = args.data_root.resolve()
    output_dir = args.output_dir.resolve()

    require_training_files(data_root)
    config = build_config(args)
    config_path = write_config(config, output_dir)

    print(f"Wrote VietOCR config: {config_path}")
    print(f"Expected exported weights: {output_dir / 'transformerocr.pth'}")

    if args.write_config_only:
        print("Config-only mode. Training was not started.")
        return

    train(config, pretrained=not args.no_pretrained)
    print("")
    print("VietOCR fine-tuning finished.")
    print(f"Deployment contract config: {output_dir / 'config.yml'}")
    print(f"Deployment contract weights: {output_dir / 'transformerocr.pth'}")


if __name__ == "__main__":
    main()
