import argparse
from pathlib import Path

from ultralytics import YOLO


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATA_YAML = REPO_ROOT / "datasets" / "vintext_yolo" / "data.yaml"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "weights" / "yolo_vintext"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Train YOLO text detector on the prepared VinText YOLO dataset."
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=DEFAULT_DATA_YAML,
        help="Path to YOLO data.yaml generated by prepare_vintext_yolo.py.",
    )
    parser.add_argument(
        "--model",
        default="yolo11n.pt",
        help="Base YOLO model or checkpoint path.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=80,
        help="Number of training epochs.",
    )
    parser.add_argument(
        "--imgsz",
        type=int,
        default=960,
        help="Training image size.",
    )
    parser.add_argument(
        "--batch",
        type=int,
        default=8,
        help="Batch size. Lower this if GPU memory is not enough.",
    )
    parser.add_argument(
        "--device",
        default="0",
        help="Training device, e.g. 0, cpu, or 0,1.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=4,
        help="Number of dataloader workers.",
    )
    parser.add_argument(
        "--project",
        type=Path,
        default=DEFAULT_OUTPUT_DIR.parent,
        help="Ultralytics project directory.",
    )
    parser.add_argument(
        "--name",
        default=DEFAULT_OUTPUT_DIR.name,
        help="Ultralytics run name. Keep yolo_vintext for deployment contract.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume training from the run directory if supported by Ultralytics.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    data_yaml = args.data.resolve()
    if not data_yaml.exists():
        raise FileNotFoundError(
            f"Missing data.yaml: {data_yaml}\n"
            "Run tools/prepare_vintext_yolo.py first."
        )

    model = YOLO(args.model)
    model.train(
        data=str(data_yaml),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        workers=args.workers,
        project=str(args.project.resolve()),
        name=args.name,
        exist_ok=True,
        resume=args.resume,
    )

    expected_best = args.project.resolve() / args.name / "weights" / "best.pt"
    print("")
    print("YOLO VinText training finished.")
    print(f"Expected best checkpoint: {expected_best}")
    print("")
    print("Deployment contract:")
    print(f"  YOLO_VINTEXT_BEST={expected_best}")
    print("  Copy or reference this file as weights/yolo_vintext/best.pt")


if __name__ == "__main__":
    main()
